export const AWAY = 'Away';
export const CLASS_NAME = 'Class';
export const HOME = 'Home';
export const NAME = 'Name';
export const SCORE = 'Score';
export const SORT = 'Sort';
export const STATUS = 'Status';
export const START_TIME = 'Start time';
export const TYPE_NAME = 'Type';
